# Generated by Django 5.1.6 on 2025-02-08 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(blank=True, default='static/profile_pics/default_pp.jpg', null='True', upload_to='static/profile_pics/'),
        ),
    ]
